# Generated by Django 5.2.1 on 2025-05-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("ProfilePic", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=20)),
                ("admitDate", models.DateField()),
                ("diease", models.IntegerField()),
                ("doctor", models.IntegerField()),
            ],
        ),
    ]
