# Generated by Django 5.2.1 on 2025-05-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dieases", "0001_initial"),
        ("Patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="diease",
        ),
        migrations.AddField(
            model_name="patient",
            name="diease",
            field=models.ManyToManyField(to="Dieases.dieases"),
        ),
    ]
