# Generated by Django 5.2.1 on 2025-05-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Doctors", "0001_initial"),
        ("Patients", "0002_remove_patient_doctor_remove_patient_diease_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="doctor",
            field=models.ManyToManyField(to="Doctors.doctor"),
        ),
    ]
