# Generated by Django 5.2.1 on 2025-05-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Doctors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dieases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("DieasesPic", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("treatmentPossible", models.CharField(max_length=255)),
                ("treatmentAvgDuration", models.IntegerField()),
                ("doctors", models.ManyToManyField(to="Doctors.doctor")),
            ],
        ),
    ]
